---



---
apiVersion: v1
kind: Service
metadata:
  name: prod-service-app
  namespace: prod
spec:
  selector:
    app: prod-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000